-- Clean Supabase schema for the SDU cold-email application.
-- Browser roles receive no table access; the FastAPI backend uses the service-role key.

create table public.leads (
  id text primary key,
  company_name text not null,
  contact_email text not null,
  contact_name text not null default '',
  website text not null default '',
  industry text not null default '',
  notes text not null default '',
  country text not null default '',
  phone text not null default '',
  stage text not null default 'new_lead',
  services text[] not null default '{}',
  internal_notes text not null default '',
  last_contact_at timestamptz,
  subject text not null default '',
  intro text not null default '',
  status text not null default 'pending',
  provider text not null default 'resend',
  message_id text not null default '',
  error text not null default '',
  gen_ms integer not null default 0,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  delivery jsonb not null default '{}'::jsonb
);

create table public.send_logs (
  id text primary key,
  email_id text references public.leads(id) on delete set null,
  campaign_id text,
  kind text not null default 'cold_email',
  company_name text not null default '',
  contact_email text not null default '',
  subject text not null default '',
  status text not null default '',
  provider text not null default 'resend',
  message_id text not null default '',
  gen_ms integer not null default 0,
  timestamp timestamptz not null default now(),
  error text not null default '',
  event text not null default '',
  last_event_at timestamptz
);

create table public.website_cache (
  id bigint generated by default as identity primary key,
  url text not null unique,
  summary text not null default '',
  fetched_at timestamptz not null default now()
);

create table public.tasks (
  id text primary key,
  lead_id text not null default '',
  title text not null,
  due_date text not null default '',
  notes text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.meetings (
  id text primary key,
  lead_id text not null,
  date text not null,
  time text not null default '',
  outcome text not null default '',
  notes text not null default '',
  next_action text not null default '',
  created_at timestamptz not null default now()
);

create table public.timeline (
  id text primary key,
  lead_id text not null,
  kind text not null,
  title text not null,
  detail text not null default '',
  at timestamptz not null default now()
);

create table public.contact_lists (
  id text primary key,
  name text not null,
  contacts jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.campaigns (
  id text primary key,
  name text not null,
  kind text not null default 'newsletter',
  list_id text not null,
  list_name text not null default '',
  from_email text not null,
  from_name text not null default '',
  subject text not null,
  total integer not null default 0,
  sent integer not null default 0,
  failed integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  attachments_count integer not null default 0
);

create table public.app_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table public.daily_email_counts (
  day date primary key default current_date,
  sent_count integer not null default 0 check (sent_count >= 0),
  updated_at timestamptz not null default now()
);

create index leads_status_idx on public.leads(status);
create index leads_stage_idx on public.leads(stage);
create index leads_created_at_idx on public.leads(created_at desc);
create index leads_message_id_idx on public.leads(message_id) where message_id <> '';
create index send_logs_timestamp_idx on public.send_logs(timestamp desc);
create index send_logs_message_id_idx on public.send_logs(message_id) where message_id <> '';
create index send_logs_campaign_id_idx on public.send_logs(campaign_id) where campaign_id is not null;
create index tasks_lead_id_idx on public.tasks(lead_id);
create index meetings_lead_id_idx on public.meetings(lead_id);
create index timeline_lead_id_at_idx on public.timeline(lead_id, at desc);

create or replace function public.get_daily_email_count()
returns integer
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(
    (select sent_count from public.daily_email_counts where day = current_date),
    0
  );
$$;

create or replace function public.reserve_daily_email(p_limit integer)
returns boolean
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  reserved integer;
begin
  if p_limit < 1 then
    return false;
  end if;

  insert into public.daily_email_counts(day, sent_count, updated_at)
  values (current_date, 1, now())
  on conflict (day) do update
    set sent_count = public.daily_email_counts.sent_count + 1,
        updated_at = now()
    where public.daily_email_counts.sent_count < p_limit
  returning sent_count into reserved;

  return reserved is not null;
end;
$$;

create or replace function public.release_daily_email()
returns void
language sql
volatile
security invoker
set search_path = public
as $$
  update public.daily_email_counts
  set sent_count = greatest(sent_count - 1, 0), updated_at = now()
  where day = current_date;
$$;

alter table public.leads enable row level security;
alter table public.send_logs enable row level security;
alter table public.website_cache enable row level security;
alter table public.tasks enable row level security;
alter table public.meetings enable row level security;
alter table public.timeline enable row level security;
alter table public.contact_lists enable row level security;
alter table public.campaigns enable row level security;
alter table public.app_settings enable row level security;
alter table public.daily_email_counts enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on function public.get_daily_email_count() from public, anon, authenticated;
revoke all on function public.reserve_daily_email(integer) from public, anon, authenticated;
revoke all on function public.release_daily_email() from public, anon, authenticated;

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant execute on function public.get_daily_email_count() to service_role;
grant execute on function public.reserve_daily_email(integer) to service_role;
grant execute on function public.release_daily_email() to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('app-files', 'app-files', false, 10485760, array['application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
